create database PRODUCT_DB

create schema PRODUCT_DATA

create table PRODUCT_DATA.PRODUCT_SRC
(
PRODUCTID STRING,

PRODUCTNAME STRING,

CATEGORY STRING,

PRICE FLOAT,

STOCKQUANTITY FLOAT,

SUPPLIER STRING,

RATING FLOAT

)

create table PRODUCT_DATA.PRODUCT_TGT
(
PRODUCTID STRING,

PRODUCTNAME STRING,

CATEGORY STRING,

PRICE FLOAT,

STOCKQUANTITY FLOAT,

SUPPLIER STRING,

RATING FLOAT
)

CREATE OR REPLACE STREAM PRODUCT_STREAM
ON TABLE PRODUCT_DB.PRODUCT_DATA.PRODUCT_SRC
-- optional: append only if you only care about inserts
-- APPEND_ONLY = TRUE

SELECT * 
FROM PRODUCT_DB.PRODUCT_DATA.PRODUCT_STREAM;

create or replace task mytask
WAREHOUSE =  COMPUTE_WH
schedule = '1 Minute'
as
merge into PRODUCT_DATA.PRODUCT_TGT as trg
using PRODUCT_DATA.PRODUCT_STREAM as src
on src.PRODUCTID = trg.PRODUCTID
when matched and src.METADATA$ISUPDATE = true then
update set
  trg.PRODUCTNAME = src.PRODUCTNAME,
  trg.CATEGORY = src.CATEGORY,
  trg.PRICE = src.PRICE,
  trg.STOCKQUANTITY = src.STOCKQUANTITY,
  trg.SUPPLIER = src.SUPPLIER,
  trg.RATING = src.RATING
when not matched then
insert (PRODUCTID, PRODUCTNAME, CATEGORY, PRICE, STOCKQUANTITY, SUPPLIER, RATING)
values (src.PRODUCTID, src.PRODUCTNAME, src.CATEGORY, src.PRICE, src.STOCKQUANTITY, src.SUPPLIER, src.RATING);

create stage  PRODUCT_DATA.PRODUCT_STAGE

list @PRODUCT_DATA.PRODUCT_STAGE

CREATE OR REPLACE FILE FORMAT csv_product
TYPE = 'CSV'
FIELD_DELIMITER = ','      -- column separator
RECORD_DELIMITER = '\n'    -- row separator
SKIP_HEADER = 1            -- skip header row

copy into PRODUCT_DATA.PRODUCT_SRC
from @PRODUCT_DATA.PRODUCT_STAGE
file_format = csv_product

select * from PRODUCT_DATA.PRODUCT_STREAM

select * from PRODUCT_DATA.PRODUCT_TGT

SHOW TASKS LIKE 'mytask';

ALTER TASK mytask RESUME;
